version: '3'

services:
  backend:
    image: testyukta.azurecr.io/backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  web:
    image: testyukta.azurecr.io/frontend:latest
    ports:
      - "5001:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  mongo_data:
