version: '3'

services:
  backend:
    image: yuktaacr.azurecr.io/backend_${{ github.sha }}
    ports:
      - "5000:5000"
    environment:
      - .env
    depends_on:
      - mongo

  web:
    image: yuktaacr.azurecr.io/frontend_${{ github.sha }}
    ports:
      - "5001:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
