version: '3'
services:
  backend:
    build: /home/yukta/Desktop/task-demo/login-and-register-backend
    image: yuktaacr.azurecr.io/login-register-backend-image
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:  
      - .env
    networks:
      - my_network

  web:
    build: /home/yukta/Desktop/mern_app/login-and-register-app
    image: yuktaacr.azurecr.io/login-register-web-image
    ports:
      - "5001:3000"
    depends_on:
      - backend
    networks:
      - my_network

  mongo:
    # build: /home/yukta/Desktop/task-demo/login-and-register-backend
    image: yuktaacr.azurecr.io/mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network:
