version: '3'
services:
  backend:
    image: yuktaacr.azurecr.io/${{ secrets.ACR_USERNAME }}/backend:${{ github.sha }}
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:  
      - .env
    
  web:
    image: yuktaacr.azurecr.io/${{ secrets.ACR_USERNAME }}/frontend:${{ github.sha }}
    ports:
      - "5001:3000"
    depends_on:
      - backend
    
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

volumes:
  mongo_data:

