# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tf-app-yukta

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://yuktaacr.azurecr.io/
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Print image name
      run: |
       echo "Image to deploy: ${{ secrets.ACR_USERNAME }}/acr-yukta:${{ github.sha }}"
    # - name: Build and push backend container image to registry
    #   # uses: docker/build-push-action@v3
    #   run : |
    #     cd login-and-register-backend 
    #     docker build -t yuktaacr.azurecr.io/${{ secrets.ACR_USERNAME }}/backend:${{ github.sha }} .
    #     docker push yuktaacr.azurecr.io/${{ secrets.ACR_USERNAME }}/backend:${{ github.sha }}

    # - name: Build and push frontend Docker image
    #   run: |
    #    cd login-and-register-app
    #    docker build -t yuktaacr.azurecr.io/${{ secrets.ACR_USERNAME }}/frontend:${{ github.sha }} .
    #    docker push yuktaacr.azurecr.io/${{ secrets.ACR_USERNAME }}/frontend:${{ github.sha }}
        
      # with:
      #   push: true
      #   tags: yuktaacr.azurecr.io/${{ secrets.ACR_USERNAME }}/acr-yukta:${{ github.sha }}
      #   file: ./login-and-register-backend/Dockerfile
   
    - name: Build and start services using Docker Compose
      run: |
        cd login-and-register-backend  
        docker-compose up -d --build
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
  
    - name: Print image name
      run: |
       echo "Image to deploy: ${{ secrets.ACR_USERNAME }}/acr-yukta:${{ github.sha }}"
 
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tf-app-yukta'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: |
          yuktaacr.azurecr.io/${{ secrets.ACR_USERNAME }}/backend:${{ github.sha }}
