
name: Build and deploy container app to Azure Web App - tf-app-yukta

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: testyukta.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
       
    - name: Build and push frontend image to registry
      uses: docker/build-push-action@v3
      with:
         context: . 
         push: true
         tags: testyukta.azurecr.io/frontend:latest
         file: /login-and-register-app/Dockerfile

    - name: Build and push backend image to registry
      uses: docker/build-push-action@v3
      with:
         context: . 
         push: true
         tags: testyukta.azurecr.io/backend:latest
         file: /login-and-register-backend/Dockerfile
  
