name: 'Terraform CI/CD'

on:
  push:
    branches: 
      - master
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest  # Specify the type of virtual environment
    env: 
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      
    environment: dev

    # Use the Bash shell regardless of the GitHub Actions runner
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Configure Terraform backend
        run: 
            echo "terraform { \
              backend \"azurerm\" { \
                storage_account_name = \"terraformyukta\" \
                container_name       = \"tfstate\" \
                key                  = \"terraform.tfstate\" \
                tenant_id            = \"$ARM_TENANT_ID\" \
                client_id            = \"$ARM_CLIENT_ID\" \
                client_secret        = \"$ARM_CLIENT_SECRET\" \
              } \
            }" > backend.tf

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
     

      # Initialize a new or existing Terraform working directory
      - name: Terraform Init
        run: terraform init
        working-directory: "./terraform"

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: "./terraform"
        
      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan 
        continue-on-error: true
        working-directory: "./terraform"
        
      # On push to "master", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud".
      # See the documentation on "strict" required status checks for more information:
      # https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' 
        run: terraform apply -auto-approve 
        working-directory: "./terraform"
